version: '1'
services:
  db:
    image: mysql:latest
    container_name: db_server
    volumes:
      - ./data:/var/lib/mysql
    restart: always
    env_file:
    - ./app.env
  app:
    depends_on:
      - db
    image: wordpress:latest
    container_name: app
    ports:
      - "8080:80"
    restart: always
    volumes:
      - ./src:/var/www/html
    env_file:
      - ./app.env
volumes:
  wordpress:
  db:
