name: ci

on:
  push:
    branches: master

jobs:
  login:
    runs-on: ubuntu-latest
    steps:
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_AUTHEN }}
      - 
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: namnv1706/namnv:ubuntu-latest
