name: ci

on:
  push:
    branches: main

jobs:
  login:
    runs-on: ubuntu-latest
    steps:
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_USER_TOKEN }}
      - 
        name: Build image
        uses: actions/checkout@v2
        run: docker build -t namnv1706/namnv:ubuntu-latest .
      -
        name: Update docker image
        run: docker push namnv1706/namnv:ubuntu-latest
